### PR TITLE
Update Mapnik-Vector-Tile

### PR DESCRIPTION
**Pull request by pnorman**
There are some errors with the latest mapnik and `make check`, but `make` builds with ubuntu 14.04, boost 1.56, and mapnik/mapnik@879e9d517bcca8ebc38908d9f47e9054a58262cb

### CODE REVIEW

**Comment by zerebubuth** [comment]
We'll have to address those `make check` errors before we consider a merge. Let's do that in MQMAP-41, which is scheduled in a couple of sprints time.

**Comment by pnorman** [comment]
Yep - don't need `make check` for the benchmarking I'm doing, but I will paste in the compile error when I get a chance.

**Comment by pnorman** [comment]
for reference, since I had a VM up
```
ubuntu@ip-172-31-12-83:~/src/avecado$ make check
make  check-am
make[1]: Entering directory `/home/ubuntu/src/avecado'
make  test/make_vector_tile test/generalizer test/adminizer test/multi_verification test/unionizer test/render_vector_tile test/overzoom test/http test/http_cache test/tilejson test/post_processor test/util_tile
make[2]: Entering directory `/home/ubuntu/src/avecado'
  CXXLD    test/make_vector_tile
test/make_vector_tile.o: In function `mapnik::json::feature_generator_grammar<std::back_insert_iterator<std::string>, mapnik::feature_impl>::feature_generator_grammar()':
/home/ubuntu/mapnik/include/mapnik/json/feature_generator_grammar_impl.hpp:34: undefined reference to `mapnik::json::properties_generator_grammar<std::back_insert_iterator<std::string>, mapnik::feature_impl>::properties_generator_grammar()'
collect2: error: ld returned 1 exit status
make[2]: *** [test/make_vector_tile] Error 1
make[2]: Leaving directory `/home/ubuntu/src/avecado'
make[1]: *** [check-am] Error 2
make[1]: Leaving directory `/home/ubuntu/src/avecado'
make: *** [check] Error 2
```

**Comment by pnorman** [comment]
to-do: update commit of mapnik in readme

**Comment by zerebubuth** [comment]
Merged #62, which has been tested with a more recent version of Mapnik.
